/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#6b4200",
        "inverse-primary": "#006b5a",
        "on-primary": "#00382e",
        primary: "#46f1cf",
        "on-primary-fixed": "#00201a",
        "surface-container-low": "#061b3a",
        "primary-fixed-dim": "#27dfbe",
        "on-secondary-container": "#551000",
        background: "#001330",
        "on-tertiary-fixed": "#2a1700",
        tertiary: "#ffcf99",
        error: "#ffb4ab",
        "surface-variant": "#223555",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb95f",
        "error-container": "#93000a",
        "primary-fixed": "#55fcda",
        "surface-container-high": "#172a49",
        "secondary-container": "#ff5627",
        "on-secondary-fixed-variant": "#881f00",
        "on-tertiary": "#472a00",
        "on-secondary-fixed": "#3b0800",
        outline: "#84948f",
        "surface-container-lowest": "#000d26",
        "on-primary-container": "#005648",
        "surface-dim": "#001330",
        "on-secondary": "#601300",
        "on-background": "#d7e2ff",
        "tertiary-fixed": "#ffddb8",
        "primary-container": "#00d4b4",
        secondary: "#ffb5a1",
        "on-primary-fixed-variant": "#005143",
        "on-tertiary-fixed-variant": "#653e00",
        surface: "#001330",
        "surface-container-highest": "#223555",
        "on-surface": "#d7e2ff",
        "inverse-on-surface": "#1e3050",
        "surface-tint": "#27dfbe",
        "secondary-fixed-dim": "#ffb5a1",
        "on-surface-variant": "#bacac4",
        "surface-bright": "#27395a",
        "inverse-surface": "#d7e2ff",
        "on-error": "#690005",
        "secondary-fixed": "#ffdbd1",
        "outline-variant": "#3b4a45",
        "surface-container": "#0b1f3e",
        "tertiary-container": "#ffaa2e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        "container-padding": "24px",
        "panel-gap": "12px",
        base: "4px",
        "layout-max-width": "1600px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "data-sm": ["JetBrains Mono", "monospace"],
        "display-md": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "400" }],
        "display-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
